name: Build for iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        architecture: ARM64

    - name: Install dependencies
      run: flutter pub get

    - name: Accept Xcode license
      run: sudo xcodebuild -license accept

    - name: Disable code signing config
      run: |
        sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/g' ios/Runner.xcodeproj/project.pbxproj
        sed -i '' 's/CODE_SIGN_IDENTITY = .*;/CODE_SIGN_IDENTITY = "";/g' ios/Runner.xcodeproj/project.pbxproj
        sed -i '' 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' ios/Runner.xcodeproj/project.pbxproj

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Package IPA
      run: |
        xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive \
          -exportPath build/ios/ipa \
          -exportOptionsPlist ios/ExportOptions.plist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOS-release
        path: build/ios/ipa
