name: Build for iOS

on:
  workflow_dispatch:

jobs:
  build:
    name: Release IOS
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.16.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Xcode license
        run: sudo xcodebuild -license accept

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign
          ln -sf ./build/ios/iphoneos Payload
          # 给framework做临时空签名，让自签工具可以识别
          find Payload/Runner.app/Frameworks -type d -name "*.framework" -exec codesign --force --sign - --preserve-metadata=identifier,entitlements {} \;
          zip -r9 Flutter_TVBox_ios.ipa Payload/Runner.app

      - name: Upload ios release
        uses: actions/upload-artifact@v4
        with:
          archive: false
          name: iOS-release
          path: Flutter_TVBox_ios.ipa
